### ISSUE TITLE
[BUG] The stylesheet portion of the HTML5 tool is not working in the PowerBI web environment. It worked last night, but appears to no be available as an option any more. This is occurring on multiple reports this morning:

### ISSUE THREAD

**Issue by silaryn** [dm-p/powerbi-visuals-html-content#51] opened 2021-12-15 13:15 UTC
The stylesheet option for the HTML5 tool inn Power BI web is not available this morning. It was there last night, but gone today.  This is occuring on multiple reports today. 

**To Reproduce**
If you look at the visual settings on the html5 tool, the smartsheet option is gone when using PowerBI on the web

**Expected behavior**

**Screenshots/Workbook**

If applicable, attach screenshots or a sample workbook with data suitable for public viewing to help explain your problem.

**Power BI Setup (please complete the following information):**
 - Platform: [e.g. Power BI Desktop, Power BI Service]

**Visual Information (please complete the following information, available by right-clicking the visual in Power BI and selecting *About*):**
 - Version: [e.g. 2.0.0.0]

**Additional context**

**Comment by dm-p** [comment] 2022-04-28 21:44
Apologies for missing this. I believe that it might be the same as #58, which is due to be fixed by MS in Power BI Desktop very soon. If this is not the same, please reopen with some supporting details to help me reproduce the issue and I can take a look for you.

**Closed by dm-p** 2022-04-28 21:44 UTC
Labels: duplicate
